#!/bin/sh --
# by pts@fazekas.hu at Mon Dec  7 14:58:29 CET 2020
#
# Tested on host system: Ubuntu 18.04.
#
# TODO(pts): sudo apt-get install -y systemd-container  # For systemd-nspawn.
# TODO(pts): sudo apt-get install -y ip  # For iproute2.
# !! TODO(pts): timezone
# !! TODO(pts): /etc/default/locale ?
# !! TODO(pts): Add "$HOSTNETIP host" to /etc/hosts
# !! TODO(pts): Use DNS resolver on the host? Unfortunately, it's not listening:
#               `nc -v 192.168.0.90 53': nc: connect to 192.168.0.90 port 53 (tcp) failed: Connection refused
#

if test -z "$RUNN_RERUN"; then
  unset S
  test "$(id -u)" != 0 && S='sudo --'
  exec $S /usr/bin/env -i TZ="$TZ" RUNN_RERUN=1 /bin/sh "$0" "$@"
  exit 1
fi

if test $# != 1 || test "$1" = "--help"; then
  echo "Usage: $0 <container-name>" >&2
  exit 1
fi
CODIR="${0%/*}"
cd "$CODIR" || exit 2
LINE=

CONAME="$1"
if ! test -d "$CONAME.container/rootfs"; then
  echo "fatal: missing rootfs directory: $CODIR/$CONAME.container/rootfs"
  exit 2
fi
case "$CONAME" in
 *[^-_a-zA-Z0-9]* | "") echo "fatal: bad container name: $CONAME"; exit 1 ;;
esac

if machinectl show "$CONAME" 2>/dev/null; then  # Early exit.
  echo "fatal: container already running: $CONAME" >&2
  exit 2
fi

if ! perl -e0 2>/dev/null; then
  echo "fatal: perl doesn't work" >&2
  exit 2
fi

if ! read HOSTNETIP <conconj.hostnet 2>/dev/null; then
  echo "fatal: missing or empty: $CODIR/conconj.hostnet"
fi
# Example: HOSTNETIP=192.168.0.90 NETDIEV=wlp2s0
NETDEV="$(ip -o addr | perl -we 'use integer; use strict;
    die "fatal: bad hostnetip: $ARGV[0]" if $ARGV[0] !~ m@\A(\d+)[.](\d+)[.](\d+)[.](\d+)(?:/32)?\Z(?!\n)@;
    my $hostnetip = unpack("N", pack("C4", $1, $2, $3, $4));
    my $netdev;
    while (<STDIN>) { chomp; my @l = split; if (@l > 3 and $l[2] eq "inet" and $l[1] ne "lo" and $l[3] =~ m@\A(\d+)[.](\d+)[.](\d+)[.](\d+)/(\d+)\Z(?!\n)@ and $5 != 32 and $5 >= 8 and $5 <= 32) {
      my $ip = unpack("N", pack("C4", $1, $2, $3, $4)); my $mask = unpack("N", pack("N", -1 << (32 - $5))); if (($ip & $mask) == ($hostnetip & $mask)) {
        die "fatal: multiple network devices for hostnetip: $ARGV[0]\n" if defined($netdev);
        $netdev = $l[1]; } } }
    die "fatal: missing network device for hostnetip: $ARGV[0]\n" if !defined($netdev);
    print "$netdev\n"' -- "$HOSTNETIP")"
test "$NETDEV" || exit 2

UR=
read UR </proc/sys/kernel/osrelease  # It's OK to fail.
if test "$UR" && test -d /lib/modules/"$UR"; then
  BM="--bind-ro /lib/modules/$UR"
else
  # TODO(pts): Disallow whitespace in $UR.
  BM=
fi

ISSR=
while read LINE; do
 case "$LINE" in
  nameserver\ 127.0.0.53) ISSR=1   # systemd-resolved.
 esac
done <"$CONAME".container/rootfs/etc/resolv.conf
if test "$ISSR"; then
  LINE="$(systemd-resolve --status "$NETDEV")"  # Network interface.
  case "$LINE" in
   *DNS\ Servers:\ *) ISSR=2 ;;
  esac
fi
if test "$ISSR" = 2 && test -f "$CONAME".container/rootfs/etc/systemd/resolved.conf; then
  # Copy over host systemd-resolved config to container.
  echo "$LINE" | perl -ni -we 'use integer; use strict; our %conf; our %confhad; BEGIN { $conf{DNS} = ""; $conf{MulticastDNS} = "no"; $conf{DNSSEC} = "no"; $conf{LLMNR} = "no"; my $key = ""; while (<STDIN>) { s@^\s+@@; if (s@(.*?): @@) { $key = $1 } chomp; if ($key eq "DNS Servers") { $conf{DNS} .= " " if length($conf{DNS}); $conf{DNS} .= $_; } elsif ($key =~ m@^(\S+) setting$@ and exists($conf{$1})) { $conf{$1} = $_ } }; $conf{LLMNR} = "no" } $_ .= "\n" if !m@\n@; if (m@^#?([^\s#=]+)=@ and exists($conf{$1})) { print "$1=$conf{$1}\n"; $confhad{$1} = 1 } else { print } END { for (sort(keys(%conf))) { print "$_=$conf{$_}\n" if !exists($confhad{$_}) } }' "$CONAME".container/rootfs/etc/systemd/resolved.conf || exit 2
  # TODO(pts): Fix non-systemd `nameserver' also in /etc/resolv.conf
fi

(ip -o addr show hostnet 2>/dev/null | while read A B C D E; do
  if test "$B" = hostnet && test "$C" = inet && test "$D" != "$HOSTNETIP/32"; then
    echo "fatal: device hostnet already up, with IP address ${D%/*}, should be: $HOSTNETIP" >&2
    exit 2
  fi
done) || exit 2

if ! ip link show hostnet >/dev/null 2>&1; then
  # https://unix.stackexchange.com/q/622914
  # `type macvlan' works on Etherenet only (no wifi), `type ipvlan mode l2' works everywhere.
  # ipvlan vs macvlan: https://sreeninet.wordpress.com/2016/05/29/macvlan-and-ipvlan/
  # ip link del hostnet ||:
  ip link add hostnet link "$NETDEV" type ipvlan mode l2 || exit 2
  ip addr add "$HOSTNETIP"/32 brd + dev hostnet || exit 2
  ip link set hostnet up || exit 2  # `ip route add' below needs it.
fi

GUESTIP=
read GUESTIP <"$CONAME".container/ipaddr 2>/dev/null ||:

GUESTNETNS=guest."$CONAME"
#ip netns del "$GUESTNETNS" && sleep .5 ||:
if ! (ip netns list | while read A B; do test "$A" = "$GUESTNETNS" && exit 0; done); then
  # Network namespace $GUESTNETNS doesn't exist, create it.
  ip netns add "$GUESTNETNS" || exit 2
  ip -n "$GUESTNETNS" link set lo up || exit 2
fi

ip link del "$GUESTNETNS"in 2>/dev/null ||:
ip -n "$GUESTNETNS" link del "$GUESTNETNS"in 2>/dev/null ||:
if test "$GUESTIP"; then
  NETMASKBITS=24  # !!
  echo a1
  ip link add link "$NETDEV" name "$GUESTNETNS"in type ipvlan mode l2 || exit 2
  echo a1b
  ip link set "$GUESTNETNS"in netns "$GUESTNETNS" || exit 2
  echo a2
  #ip -n "$GUESTNETNS" link set "$GUESTNETNS"in down || exit 2  # Doesn't remove IP addresses.
  #ip -n "$GUESTNETNS" addr flush dev "$GUESTNETNS"in || exit 2
  #ip -n "$GUESTNETNS" route del default 2>/dev/null ||:
  #ip -o -n "$GUESTNETNS" addr show "$GUESTNETNS"in; while read A B C D E; do
  #  if test "$3" = inet && test "${4%/*}" = "$GUESTIP"; then
  #    ip -n "$GUESTNETNS" ip addr del "$GUESTIP/$NETMASKBITS" dev "$GUESTNETNS"in || exit 2
  #  fi
  #done
  echo a3
  ip -n "$GUESTNETNS" addr add "$GUESTIP/$NETMASKBITS" brd + dev "$GUESTNETNS"in || exit 2
  echo a4
  ip -n "$GUESTNETNS" link set "$GUESTNETNS"in up || exit 2
  echo a5
  ip -n "$GUESTNETNS" route add default via 192.168.0.1 || exit 2
  echo a6
  test "$(ip route show "$GUESTIP"/32)" && ip route del "$GUESTIP"/32
  ip route add "$GUESTIP"/32 dev hostnet || exit 2
fi

echo qqqq; exit

# Seems to be starting in the background.
exec 9>"$CONAME".container/console.out.tmp </dev/null
systemd-nspawn --boot --directory "$CONAME".container/rootfs \
    $BM --network-namespace-path /var/run/netns/net92 \
    --machine "$CONAME" >&9 2>&9 &
exec 9>&1
while ! read LINE <"$CONAME".container/console.out.tmp; do :; done
E=
#if machinectl show -- "$CONAME" >/dev/null; then
#read LINE <"$CONAME".container/console.out.tmp || exit 1
case "$LINE" in
 Directory\ tree\ *\ is\ currently\ busy*) E=1 ;;
 Spawning\ *) ;; *) E=2 ;;
esac
#else
#  E=1
#fi
if test "$E"; then
  if test "$E" = 1; then
    # TODO(pts): Also check it by name with a different directory.
    echo "info: shoutdown gracefully: sudo machinectl poweroff $CONAME" >&2
    echo "fatal: container already running: $CONAME" >&2
  else
    cat "$CONAME".container/console.out.tmp >&2
    rm -f "$CONAME".container/console.out.tmp
  fi
  exit 2
fi
mv "$CONAME".container/console.out.tmp "$CONAME".container/console.out

# Perhaps it's too early (race condition) for poweroff or shell now.
echo "info: started; shoutdown gracefully: sudo machinectl poweroff $CONAME" >&2
echo "info: root shell: sudo machinectl shell $CONAME" >&2
exit 0
